### ISSUE TITLE
Failes silently when there are command line options after the command

### ISSUE THREAD

**Issue by dlech** [ev3dev/brickstrap#35]
It used to not matter what order the options or commands are in. Now, if you have an option, e.g. `-f` after the command in the command line, brickstrap fails silently.

**Comment by cmacq2** [comment]
The bug is easy to fix: after shifting with `shift $((OPTIND-1))` we need to check that `$# -ge 1` (i.e that at least one more argument remains) or else you have the problem that the last `shift 1` will error out.

This bug is basically in old copy pasted code and presumably it went undetected because it triggers only if you put the command in second to last position.

I'll update PR #29 with a fix.

**Comment by cmacq2** [comment]
Since PR #29 has been merged, this issue can be closed now.
